### ISSUE TITLE
Select-Operation of AirTable-node with OutputType = "All records in 1 array" puts out more than one array

### ISSUE THREAD

**Issue by DominikHirsch** [joeartsea/node-red-contrib-airtable#10]
I am using the select-operation of the air-table-node and i set the OutputType of the node to "All records in 1 array".
My problem is that the node outputs more than one array, as soon as the AirTable table has more than 100 records and the next node gets two output messages.

My question is: is there a way to get all of the records within one array even if the AirTable table consists of more than 100 records?

**Comment by Hugobox** [comment]
There's a fix included for this problem by Ralrom in the pull request https://github.com/joeartsea/node-red-contrib-airtable/pull/9
