### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined - Find mode

### ISSUE THREAD

**Issue by ghost** [joeartsea/node-red-contrib-airtable#11]
In an inject node I'm passing a JSON with the record id and its value to do a find {"id":"recNsJci9RVq0uvMY"}, what is the value that returns to me with a selectand, it gives me the following error: TypeError: Cannot read property 'id' of undefined 

I tried to pass it as a string and I got the same error

**Comment by Hugobox** [comment]
Hi @Carbarsen !
Try to set msg.recId with your id as a string,gfor example in a change node: 
![image](https://user-images.githubusercontent.com/15982264/92649137-8f483600-f2b8-11ea-97e2-a34574a2a565.png)

**Comment by ghost** [comment]
Hi @Hugobox 
 Same error
<img width="460" alt="Error" src="https://user-images.githubusercontent.com/69509072/92721301-29b28300-f366-11ea-84b5-8b47875b9444.png">

Attach flow

`[{"id":"a5da33be.7c6198","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"be5cb24d.7c174","type":"airtable out","z":"a5da33be.7c6198","airtable":"2e2202d.965ef7e","operation":"find","outputType":"multiple","table":"Person","name":"Find","x":470,"y":60,"wires":[["b90f79bd.4b8eb8"]]},{"id":"b90f79bd.4b8eb8","type":"debug","z":"a5da33be.7c6198","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":670,"y":60,"wires":[]},{"id":"e2677700.0fda28","type":"inject","z":"a5da33be.7c6198","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{}","payloadType":"str","x":120,"y":60,"wires":[["87b49132.62b81"]]},{"id":"87b49132.62b81","type":"change","z":"a5da33be.7c6198","name":"","rules":[{"t":"set","p":"recid","pt":"msg","to":"rect0whWYELr7TNOp","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":60,"wires":[["be5cb24d.7c174"]]},{"id":"2e2202d.965ef7e","type":"airtable","z":"","name":"AitableFM"}]`

**Comment by Hugobox** [comment]
Try to set msg.recId with an uppercase i.

**Comment by ghost** [comment]
Solved, thanks
