### ISSUE TITLE
Node-red V1.03 with "select" - messages point to same object

### ISSUE THREAD

**Issue by willhey** [joeartsea/node-red-contrib-airtable#3]
The select option returns a series of messages, which look OK in the debug node, but other nodes only have a pointer to the last record.  I think it is Asynchronous message passing, new in v1 of node-red.  My solution was to change 
node.sendMsg(null, record); //line 78 of airtable.js
to
var msg={payload:record};
node.send(msg);

Mike

**Comment by Hugobox** [comment]
It would be nice if there was an option to output an array instead of 1 message per record.

**Comment by Hugobox** [comment]
Please look at pull request! Thanks!
